name: 'D-day Labeler'
description: '매일 이슈의 D-n 라벨을 ↓1씩, D-day→Overdue 처리하는 액션'

branding:
  icon: "calendar"
  color: "blue"

inputs:
  token:
    description: "GitHub token"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
